version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: log
      MYSQL_USER: MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/log?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - default

#  test:
#    depends_on:
#      - spring-app
#    build:
#      context: .
#      dockerfile: TestDockerfile
#    networks:
#      - default
